### ISSUE TITLE
Botão enviar disabled na configuração de produtos do webhook

### ISSUE THREAD

**Issue by Iagofelicio** [multicanais/sintegre-webhook#3]
Dentro das configurações de seleção dos produtos do webhook tem alguns itens que estão com o botão **Enviar** _Disabled_. Estes produtos estão com algum problema ou pretendem ser disponibilizados em breve? 

Imagem de exemplo (Previsão de Precipitação): https://imgur.com/IYL5GGR

**Comment by multicanais** [comment]
Este é um produto dinâmico e estava na lista para notificações/webhook por engano, todos os produtos dinâmicos já foram removidos das notificações/webhook.
 
Produtos dinâmicos não possuem um marco de publicação e por natureza devem permitir consultas dinâmicas aos conteúdos de todos os períodos disponíveis, não possuímos uma mecânica de notificação de conteúdo atualizado para estes casos, por enquanto.
