### ISSUE TITLE
Senha ao abrir PDF

### ISSUE THREAD

**Issue by Regin0** [multicanais/sintegre-webhook#4]
Quando tento abrir um arquivo baixado através do WebHook, é pedido uma senha, não fica claro na documentação qual devo usar.

**Comment by multicanais** [comment]
Qual produto e de qual referência está tentando abrir?

----- Mensagem original -----
De: "Regino" <notifications@github.com>
Para: "multicanais/ons-sintegre-webhook" <ons-sintegre-webhook@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Assunto: [multicanais/ons-sintegre-webhook] Senha ao abrir PDF (#4)
Data: ter, 3 de dez de 2019 14:06
 
Quando tento abrir um arquivo baixado através do WebHook, é pedido uma senha, não fica claro na documentação qual devo usar.

**Comment by Regin0** [comment]
É o arquivo de IPDO, que retorna um PDF, porém, a senha só é pedida quando baixada através do exemplo em Node.js disponibilizado neste repositório.

**Comment by Regin0** [comment]
Corrigido.
O problema ocorria devido a concatenação da stream em uma string, passei a criar uma stream direto da resposta e agora está salvando corretamente.
```js
    const file = fs.createWriteStream(`${path}/${filename}`);
    response.pipe(file);
```
